config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users, shallow: true do 
    resources :chirps, shallow: true
  end
  
  resources :sessions, only: [:create]

  get '/', to: 'application#home_login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#clear'

  post '/chirps', to: 'chirps#create'
  get '/chirps/:id', to: 'chirps#show'

  #get '/users/:user_id/chirps/private', to: ''
  #get '/users/:user_id/chirps/', to: ''

  get '/auth/:provider/callback', to: 'sessions#create_session_omniauth'
  get '/users/:id/privatechirps', to: 'users#private'

  get '/all_users', to: 'users#all_users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ActiveRecord::Base
    belongs_to :user
    belongs_to :tag

    validates :user_id, presence: true
    validates :content, presence: true
    validates :sub_tag, presence: true

    def recent 
        self.last(5)
    end

    scope :setto_private, -> { where(private: true) }
    scope :setto_public, -> { where(private: false) }

    #@private_chirps = @user.chirps.setto_private
end 

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :chirps
    has_many :users, through: :chirps
end 

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :username, uniqueness: true
    validates :username, presence: true

    validates :email, uniqueness: true
    validates :email, presence: true
    
    has_many :chirps
    has_many :tags, through: :chirps
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :get_logged_user

    def get_logged_user
        session[:id] ? @logged_user = User.find(session[:id]) : false
    end 

    def home_login
        if session
            #redirect_to :"/user/#{session[:id]}"
        else
            
        end 
        render :login
    end
end

app/controllers/chirp_contoller.rb
class ApplicationController < ApplicationController

    def view
    
    end
    
    def new

    end

    def index

    end

    def create

    end

end 

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController

    def show
        @chirp = Chirp.find(params[:id])

        if session[:id] == @chirp.user_id
            render :show
        elsif @chirp.private == true
            render :'private'
        end

    end

    def index
        @user = User.find(params[:user_id])
        @chips = @user.chirps.setto_public
        render :all_chirps
    end
    
    def new
        @chirp = Chirp.new
        
        if session[:id]
            render :create_chirp
        else 
            redirect_to "/"
        end 
    end

    def create
        @chirp = Chirp.new
        @chirp.sub_tag = params[:chirp][:sub_tag]
        @chirp.content = params[:chirp][:content]
        params[:chirp][:private].to_i == 1 ? @chirp.private = true : @chirp.private = false
        @chirp.user = User.find(session[:id])
        @chirp.tag_id = params[:chirp][:tag_id]

        if @chirp.save
            redirect_to "/chirps/#{@chirp[:id]}"
        else 
            render :create_chirp
        end 
    end
end 

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

    def view
    
    end
    
    def new

    end

    def create

    end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create 
        if params[:user][:username].include?("@")
            user = User.find_by(email: params[:user][:username])
            
            if user.try(:authenticate, params[:user][:password])
                session[:id] = user.id
                session[:username] = user.username
                session[:status] = "created"
                session[:logged_in] = true
                redirect_to user_path(user)
            else 
                render_fail()
            end 
        else 
            user = User.find_by(username: params[:user][:username])
            if user.try(:authenticate, params[:user][:password])
                session[:id] = user.id
                session[:username] = user.username
                session[:status] = "created"
                session[:logged_in] = true
                redirect_to user_path(user)
            else 
                render_fail()
            end 
        end
    end 

    def create_session_omniauth
        @user =
            User.find_or_create_by(uid: auth['uid']) do |u|
                #byebug
                u.username = auth['info']['name']
                u.email = auth['info']['email']
                u.password = SecureRandom.hex(12)
            end

        session[:id] = @user.id
        #byebug
        redirect_to @user
    end 

    def clear
        session.clear
        redirect_to '/'
    end 

    private

    def auth
        request.env['omniauth.auth']
    end

    def render_fail
        params[:message] = "So Sorry but we cant locate that username/email and password combination"
        render :login
    end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        #byebug
        render :profile
    end

    def new
        @user = User.new
        render :create_user
    end

    def create
        @user = User.new
        @user.username = params[:user][:username]
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password]

        if @user.valid?
            @user.save
            redirect_to '/'
        else 
            render :create_user
        end 
    end 

    def private
        @user = User.find(session[:id])
        @chirps = @user.chirps.setto_private
        render :private_chirps
    end  
    
    def all_users
        @users = User.all
        render :all_users
    end 

    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in_nav

        @logged_user = User.find(session[:id])

        if session[:id]
            `<div id="top-bar" style="width: 100%; background-color: grey; color: white; height: 20px; margin: 0; padding: 20px 50px;">
              <a href="/users/<%=session[:id]%>/chirps/new"> <button>Create Chirp</button></a> <button>notifications</button>
            </div>`
        end
    end 
end

app/helpers/chirp_helper.rb
module ChirpHelper

    def user_owns_chirp
        session[:id] == @chirp.user_id
    end 

end

app/helpers/layouts_helper.rb
module LayoutsHelper

    def show_logged_in_nav

        logged_user = User.find(session[:id])

        if session[:id]
            `<div id="top-bar" style="width: 100%; background-color: grey; color: white; height: 20px; margin: 0; padding: 20px 50px;">
              <a href="/users/<%=session[:id]%>/chirps/new"> <button>Create Chirp</button></a> <button>notifications</button>
            </div>`
        end
    end 

end

app/helpers/user_helper.rb
module UserHelper

    

end

app/views/application/login.html.erb
<h2>Login</h2>

<%= form_tag '/login', mthod: :get do%>
<% if params[:message] != "" %>
    <p><%=params[:message]%></p>
<%end%>
    <label>Username or Email:</label>
    <%= text_field_tag :'user[username]'%>
    <br>
    <br>
    <label>Password:</label>
    <%= text_field_tag :'user[password]'%>
    <br>
    <br>
    <input type="submit"  value="login">
    <br>
<%end%>

<p><%= button_to 'Login With GitHub', '/auth/github', method: :post %> or <a href="/users/new">Create Account<a>.</p>

app/views/chirps/all_chirps.html.erb
<style>
 a, a:hover, a:focus, a:active {
      text-decoration: none;
      color: inherit;
 }
</style>

<h2><%=@user.username%>'s Profile</h2>
<%if session[:id] == @user.id%>
    <button>All Chirps</button>&nbsp;<button>Most Recent</button>
<%end%>
<%if @user.chirps.any?%>
    <div>
        <%@user.chirps.each do |chirp|%>
            <a href="<%=chirp_path(chirp)%>">
            <div style="border-style: solid; padding: 10px; margin: 10px 0px; width: 500px;">
                <h5 style="margin: 0;">@<%=chirp.user.username%></h5>
                <p style="margin: 10px 0px 0px 0px;"><%=chirp.content%></p>
                <% if chirp.private%>
                    <p style="color: grey;"><em>Private</em></p>                
                <%end%>
            </div>
            <a>
        <%end%>
    </div>
<%else%>
    <h1>!</h1>
    <h3>This User Doesn't Have Any Chirps Yet</h3>
<%end%>

app/views/chirps/create_chirp.html.erb
<h1>Create new chirp</h1>

<% if @chirp.errors.any?%>
    <ul>
        <%@chirp.errors.full_messages.each do |error|%>
            <li><%=error%></li>
        <%end%>
    </ul>
<%end %>

<%= form_for @chirp do |f|%>
    <br>

    <label>Tag</label>
    <br>
    <%=f.collection_select(:tag_id, Tag.all, :id, :name)%>
    <br>
    <br>

    <label>Chirp Content</label>
    <br>
    <%=f.text_field :content%>
    <br>
    <br>

    <label>About</label>
    <br>
    <%=f.text_field :sub_tag%>
    <p><em>The person this chirp is about. This will be only viewable by people who guess it correctly</em></p>
    <br>
  
    <%=f.check_box :private %><label>Private?</label>
    <p><em>Will users be able to guess who the chirp is about?</em></p>
    <br><br>

    <input type="submit"  value="Create SubChirp">
<%end%>

app/views/chirps/private.html.erb
<h1>SORRY BUT THIS CHIRP IS PRIVATE</h1>

app/views/chirps/show.html.erb
<%if @chirp.private%>
    <p><em>This chirp is set to private, so only you can view it.</em><p>
<%end%>

<h2><a href="<%=user_path(@chirp.user)%>">@<%=@chirp.user.username%><a></h2>
<p><%=@chirp.content%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subchirp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body style="margin: 0;">

    <div id="top-bar" style="width: 100%; background-color: black; color: white; height: 50px; margin: 0; padding: 20px 50px;">
      <h1 style="display: inline;">SubChirp</h1>

      <%if @logged_user%>
        <p style="margin: 0;">Viewing as <a href="<%=user_path(@logged_user)%>">@<%=@logged_user.username%></a>&nbsp;|&nbsp;&nbsp;<a href="/logout">Logout</a></p>
      <%else%>
        <p style="margin: 0;"><a href="/">Login</a>&nbsp;or&nbsp;<a href="/users/new">Create Account</a></p>
      <%end%>
    </div>

    <%if @logged_user%>
      <div id="top-bar" style="width: 100%; background-color: grey; color: white; height: 20px; margin: 0; padding: 20px 50px;">
        <a href="/users/<%=session[:id]%>/chirps/new"> <button>Create Chirp</button></a> <button>notifications</button>
      </div>
    <%end%>

    <div style="padding: 20px 50px;">

    <%= yield %>

    </div>

    <footer style="width: 100%; background-color: black; color: white; height: 50px; margin: 0; padding: 20px 50px;">
      <p>Author: Jonathon McClendon<br>
      <a href="mailto:hege@example.com">JonathonsMcClendon@gmail.com</a></p>
    </footer>
  </body>
</html>

app/views/users/all_users.erb
<div>
    <%@users.each do |user|%>
        <div>
            <h2><%=link_to user.username, user%><h2>
            <p>Number of chirps: <%=user.chirps.length%></p>
        </div>
    <%end%>
<div>76

app/views/users/create_user.html.erb
<h2>Create Account</h2>

<script>

    var password1
    var password2

    window.onload = function() {
        console.log('Page is loaded');
        password1 = document.getElementById("user_password")
        password2 = document.getElementById("password_confirm")

        password2.setAttribute("onkeypress", "checkMatch()");
        password2.setAttribute("onChange", "checkMatch()");
        
    };



    function checkMatch(){

        if (password1.value != password2.value){
            document.getElementById("js_errors").innerHTML = "<p>Your Passwords Dont Match!</p>"
        } else {
            document.getElementById("js_errors").innerHTML = "&nbsp;"
        }
    }

    
</script>


<% if @user.errors.any?%>
    <ul>
        <%@user.errors.full_messages.each do |error|%>
            <li><%=error%></li>
        <%end%>
    </ul>
<%end %>


<%= form_for(@user) do |f|%>
    <label>Username</label>
    <%= f.text_field :username%>
    <br>
    <br>
    <label>Email</label>
    <%= f.text_field :email%>
    <br>
    <br>
    <label>Password</label>
    <%= f.password_field :password%>
    <br>
    <div id="js_errors">
    &nbsp;
    </div>
    <label>Confirm Password</label>
    <input type="password" id="password_confirm" name="user[password]">
    <br>
    <br>
    <input type="submit"  value="Create Account"><p> or go to <a href="/">Login</a> page.</p>
<%end%>

app/views/users/most_recent.html.erb
<style>
 a, a:hover, a:focus, a:active {
      text-decoration: none;
      color: inherit;
 }
</style>

<h2><%=@user.username%>'s Profile</h2>

<button>All Chirps</button>&nbsp;<button>Most Recent</button>
<%if session[:id] == @user.id%>
    <a href=""><button>Private</button></a>
<%end%>
<%if @user.chirps.any?%>
    <div>
        <%@user.chirps.each do |chirp|%>
            <a href="<%=chirp_path(chirp)%>">
            <div style="border-style: solid; padding: 10px; margin: 10px 0px; width: 500px;">
                <h5 style="margin: 0;">@<%=chirp.user.username%></h5>
                <p style="margin: 10px 0px 0px 0px;"><%=chirp.content%></p>
                <% if chirp.private%>
                    <p style="color: grey;"><em>Private</em></p>                
                <%end%>
            </div>
            <a>
        <%end%>
    </div>
<%else%>
    <h1>!</h1>
    <h3>This User Doesn't Have Any Chirps Yet</h3>
<%end%>

app/views/users/private_chirps.html.erb
<style>
 a, a:hover, a:focus, a:active {
      text-decoration: none;
      color: inherit;
 }
</style>

<h2><%=@user.username%>'s Profile</h2>

<a href="/users/<%=@user.id%>"><button>All Chirps</button></a>&nbsp;<button>Most Recent</button>
<%if session[:id] == @user.id%>
    <a href=""><button>Private</button></a>
<%end%>
<%if @user.chirps.setto_private.any?%>
    <div>
        <%@user.chirps.setto_private.each do |chirp|%>
            <a href="<%=chirp_path(chirp)%>">
            <div style="border-style: solid; padding: 10px; margin: 10px 0px; width: 500px;">
                <h5 style="margin: 0;">@<%=chirp.user.username%></h5>
                <p style="margin: 10px 0px 0px 0px;"><%=chirp.content%></p>
                <% if chirp.private%>
                    <p style="color: grey;"><em>Private</em></p>                
                <%end%>
            </div>
            <a>
        <%end%>
    </div>
<%else%>
    <h1>!</h1>
    <h3>This User Doesn't Have Any Chirps Yet</h3>
<%end%>

app/views/users/profile.html.erb
<style>
 a, a:hover, a:focus, a:active {
      text-decoration: none;
      color: inherit;
 }
</style>

<h2><%=@user.username%>'s Profile</h2>

<a href="/users/<%=@user.id%>"><button>All Chirps</button></a>&nbsp;<button>Most Recent</button>

<%if session[:id] == @user.id%>
    <a href="/users/<%=session[:id]%>/privatechirps"><button>Private</button></a>
<%end%>

<%if @user.chirps.any?%>
    <div>
        <%@user.chirps.each do |chirp|%>
            <a href="<%=chirp_path(chirp)%>">
            <div style="border-style: solid; padding: 10px; margin: 10px 0px; width: 500px;">
                <h5 style="margin: 0;">@<%=chirp.user.username%></h5>
                <p style="margin: 10px 0px 0px 0px;"><%=chirp.content%></p>
                <% if chirp.private%>
                    <p style="color: grey;"><em>Private</em></p>                
                <%end%>
            </div>
            <a>
        <%end%>
    </div>
<%else%>
    <h1>!</h1>
    <h3>This User Doesn't Have Any Chirps Yet</h3>
<%end%>